/**
 * TINY GENERATED CODE, DO NOT EDIT BY HAND
 * @project UTiny.Demo.DragonMatch
 */

entities.game.Level_Base.name = "Level_Base";
entities.game.Level_Base.load = function(w) {
    var e1 = w.create("Match_Bk");
    var e2 = w.create("Match_base");
    var e3 = w.create("Dragon");
    var e4 = w.create("Match_life");
    var e5 = w.create("HealthFillScaler");
    var e6 = w.create("HealthFill");
    var e7 = w.create("Match_GemBK");
    var e8 = w.create("Board");
    var e9 = w.create("Camera");
    e1.addComponent(this.Component);
    e2.addComponent(this.Component);
    e3.addComponent(this.Component);
    e4.addComponent(this.Component);
    e5.addComponent(this.Component);
    e6.addComponent(this.Component);
    e7.addComponent(this.Component);
    e8.addComponent(this.Component);
    e9.addComponent(this.Component);
    e1.addComponent(ut.layers.Default);
    e2.addComponent(ut.layers.Default);
    e3.addComponent(ut.layers.Default);
    e4.addComponent(ut.layers.Default);
    e5.addComponent(ut.layers.Default);
    e6.addComponent(ut.layers.Default);
    e7.addComponent(ut.layers.Default);
    e8.addComponent(ut.layers.Default);
    e9.addComponent(ut.layers.Default);
    var c1 = e1.addComponent(ut.Core2D.Transform);
    var s1 = c1.localPosition();
    s1.y = 194;
    c1.setLocalPosition(s1);
    var s2 = c1.localRotation();
    s2.w = 1;
    c1.setLocalRotation(s2);
    var s3 = c1.localScale();
    s3.x = 250;
    s3.y = 250;
    s3.z = 1;
    c1.setLocalScale(s3);
    var c2 = e1.addComponent(ut.Core2D.Sprite2DRenderer);
    c2.setSprite(w.getByName('assets/sprites/Match_Bk'));
    var s4 = c2.color();
    s4.r = 1;
    s4.g = 1;
    s4.b = 1;
    s4.a = 1;
    c2.setColor(s4);
    c2.setBlending(0);
    var c3 = e2.addComponent(ut.Core2D.Transform);
    var s5 = c3.localPosition();
    s5.y = -336.3999;
    c3.setLocalPosition(s5);
    var s6 = c3.localRotation();
    s6.w = 1;
    c3.setLocalRotation(s6);
    var s7 = c3.localScale();
    s7.x = 130;
    s7.y = 130;
    s7.z = 1;
    c3.setLocalScale(s7);
    var c4 = e2.addComponent(ut.Core2D.Sprite2DRenderer);
    c4.setSprite(w.getByName('assets/sprites/Match_base'));
    var s8 = c4.color();
    s8.r = 1;
    s8.g = 1;
    s8.b = 1;
    s8.a = 1;
    c4.setColor(s8);
    c4.setBlending(0);
    var c5 = e3.addComponent(ut.Core2D.Transform);
    var s9 = c5.localPosition();
    s9.y = 579;
    c5.setLocalPosition(s9);
    var s10 = c5.localRotation();
    s10.w = 1;
    c5.setLocalRotation(s10);
    var s11 = c5.localScale();
    s11.x = 79.99998;
    s11.y = 79.99998;
    s11.z = 1;
    c5.setLocalScale(s11);
    var c6 = e3.addComponent(ut.Core2D.Sprite2DRenderer);
    c6.setSprite(w.getByName('assets/sprites/Match_Dragon01'));
    var s12 = c6.color();
    s12.r = 1;
    s12.g = 1;
    s12.b = 1;
    s12.a = 1;
    c6.setColor(s12);
    c6.setBlending(0);
    var c7 = e3.addComponent(ut.Core2D.Sprite2DSequence);
    var a1 = [ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE];
    a1[0] = w.getByName('assets/sprites/Match_Dragon00');
    a1[1] = w.getByName('assets/sprites/Match_Dragon01');
    a1[2] = w.getByName('assets/sprites/Match_Dragon02');
    a1[3] = w.getByName('assets/sprites/Match_Dragon03');
    a1[4] = w.getByName('assets/sprites/Match_Dragon04');
    a1[5] = w.getByName('assets/sprites/Match_Dragon05');
    a1[6] = w.getByName('assets/sprites/Match_Dragon06');
    a1[7] = w.getByName('assets/sprites/Match_Dragon07');
    a1[8] = w.getByName('assets/sprites/Match_Dragon08');
    a1[9] = w.getByName('assets/sprites/Match_Dragon09');
    a1[10] = w.getByName('assets/sprites/Match_Dragon10');
    a1[11] = w.getByName('assets/sprites/Match_Dragon11');
    a1[12] = w.getByName('assets/sprites/Match_Dragon12');
    a1[13] = w.getByName('assets/sprites/Match_Dragon13');
    c7.setSprites(a1);
    c7.setFrameRate(5);
    var c8 = e3.addComponent(ut.Core2D.Sprite2DSequencePlayer);
    c8.setSequence(e3);
    c8.setLoop(0);
    c8.setSpeed(1);
    var c9 = e3.addComponent(game.Dragon);
    c9.setHealth(100);
    c9.setHealthFillEntity(e6);
    var c10 = e4.addComponent(ut.Core2D.Transform);
    var s13 = c10.localPosition();
    s13.y = -2.975001;
    c10.setLocalPosition(s13);
    var s14 = c10.localRotation();
    s14.w = 1;
    c10.setLocalRotation(s14);
    var s15 = c10.localScale();
    s15.x = 2.500001;
    s15.y = 1.25;
    s15.z = 1;
    c10.setLocalScale(s15);
    e3.getComponent(ut.Core2D.Transform).appendChild(e4);
    var c11 = e4.addComponent(ut.Core2D.Sprite2DRenderer);
    c11.setSprite(w.getByName('assets/sprites/Match_life'));
    var s16 = c11.color();
    s16.r = 1;
    s16.g = 1;
    s16.b = 1;
    s16.a = 1;
    c11.setColor(s16);
    c11.setBlending(0);
    var c12 = e5.addComponent(ut.Core2D.Transform);
    var s17 = c12.localPosition();
    c12.setLocalPosition(s17);
    var s18 = c12.localRotation();
    s18.w = 1;
    c12.setLocalRotation(s18);
    var s19 = c12.localScale();
    s19.x = 1.2;
    s19.y = 0.2;
    s19.z = 1;
    c12.setLocalScale(s19);
    e4.getComponent(ut.Core2D.Transform).appendChild(e5);
    var c13 = e6.addComponent(ut.Core2D.Transform);
    var s20 = c13.localPosition();
    s20.x = -0.5;
    c13.setLocalPosition(s20);
    var s21 = c13.localRotation();
    s21.w = 1;
    c13.setLocalRotation(s21);
    var s22 = c13.localScale();
    s22.x = 1;
    s22.y = 1;
    s22.z = 1;
    c13.setLocalScale(s22);
    e5.getComponent(ut.Core2D.Transform).appendChild(e6);
    var c14 = e6.addComponent(ut.Core2D.Sprite2DRenderer);
    var s23 = c14.color();
    s23.r = 1;
    s23.b = 0.04700279;
    s23.a = 1;
    c14.setColor(s23);
    c14.setBlending(0);
    var c15 = e6.addComponent(ut.Core2D.Sprite2D);
    c15.setImage(w.getByName('assets/textures/blank'));
    var s24 = c15.imageRegion();
    s24.width = 1;
    s24.height = 1;
    c15.setImageRegion(s24);
    var s25 = c15.pivot();
    s25.y = 0.5;
    c15.setPivot(s25);
    var c16 = e7.addComponent(ut.Core2D.Transform);
    var s26 = c16.localPosition();
    s26.y = 30.40001;
    c16.setLocalPosition(s26);
    var s27 = c16.localRotation();
    s27.w = 1;
    c16.setLocalRotation(s27);
    var s28 = c16.localScale();
    s28.x = 559.9999;
    s28.y = 559.9999;
    s28.z = 3;
    c16.setLocalScale(s28);
    var c17 = e7.addComponent(ut.Core2D.Sprite2DRenderer);
    c17.setSprite(w.getByName('assets/sprites/blank'));
    var s29 = c17.color();
    s29.r = 0.2926722;
    s29.g = 0.2054557;
    s29.b = 0.764151;
    s29.a = 0.6509804;
    c17.setColor(s29);
    c17.setBlending(0);
    var c18 = e8.addComponent(ut.Core2D.Transform);
    var s30 = c18.localPosition();
    s30.y = 30;
    c18.setLocalPosition(s30);
    var s31 = c18.localRotation();
    s31.w = 1;
    c18.setLocalRotation(s31);
    var s32 = c18.localScale();
    s32.x = 1;
    s32.y = 1;
    s32.z = 1;
    c18.setLocalScale(s32);
    var c19 = e8.addComponent(game.CellGraph);
    c19.setWidth(6);
    c19.setHeight(6);
    var s33 = c19.layout();
    s33.size.x = 90;
    s33.size.y = 90;
    c19.setLayout(s33);
    var c20 = e8.addComponent(game.Board);
    var c21 = e8.addComponent(game.BoardSpawn);
    var c22 = e8.addComponent(ut.Audio.AudioSource);
    c22.setClip(w.getByName('assets/audioclips/music_cinematic_darkness_falls'));
    c22.setVolume(1);
    c22.setLoop(true);
    c22.setPlaying(true);
    var c23 = e9.addComponent(ut.Core2D.Transform);
    var s34 = c23.localPosition();
    s34.y = 175;
    c23.setLocalPosition(s34);
    var s35 = c23.localRotation();
    s35.w = 1;
    c23.setLocalRotation(s35);
    var s36 = c23.localScale();
    s36.x = 1;
    s36.y = 1;
    s36.z = 1;
    c23.setLocalScale(s36);
    var c24 = e9.addComponent(ut.Core2D.Camera2D);
    c24.setHalfVerticalSize(512);
    var s37 = c24.rect();
    s37.width = 1;
    s37.height = 1;
    c24.setRect(s37);
    var s38 = c24.backgroundColor();
    s38.a = 1;
    c24.setBackgroundColor(s38);
    c24.setClearFlags(1);
    c24.setCullingMask([ut.layers.Default.cid, ut.layers.TransparentFX.cid, ut.layers.IgnoreRaycast.cid, ut.layers.Water.cid, ut.layers.UI.cid, ut.layers.PostProcessing.cid]);
    c24.setCullingMode(2);
    return [e1, e2, e3, e4, e5, e6, e7, e8, e9];
}

entities.game.GemPrefab.name = "GemPrefab";
entities.game.GemPrefab.load = function(w) {
    var e1 = w.create("Gem");
    e1.addComponent(this.Component);
    e1.addComponent(ut.layers.Default);
    var c1 = e1.addComponent(ut.Core2D.Transform);
    var s1 = c1.localPosition();
    s1.x = 250;
    s1.y = 250;
    c1.setLocalPosition(s1);
    var s2 = c1.localRotation();
    s2.w = 1;
    c1.setLocalRotation(s2);
    var s3 = c1.localScale();
    s3.x = 35;
    s3.y = 35;
    s3.z = 1;
    c1.setLocalScale(s3);
    var c2 = e1.addComponent(ut.Core2D.Sprite2DRenderer);
    c2.setSprite(w.getByName('assets/sprites/Match_Blue'));
    var s4 = c2.color();
    s4.r = 1;
    s4.g = 1;
    s4.b = 1;
    s4.a = 1;
    c2.setColor(s4);
    c2.setBlending(0);
    var c3 = e1.addComponent(game.CellGraphNode);
    var s5 = c3.cell();
    s5.x = 5;
    s5.y = 5;
    c3.setCell(s5);
    var c4 = e1.addComponent(game.Gem);
    c4.setType(0);
    var a1 = [ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE, ut.Entity.NONE];
    a1[0] = w.getByName('assets/sprites/Match_Pink');
    a1[1] = w.getByName('assets/sprites/Match_Green');
    a1[2] = w.getByName('assets/sprites/Match_Blue');
    a1[3] = w.getByName('assets/sprites/Match_LTBlue');
    c4.setPieces(a1);
    var s6 = c4.dragStart();
    c4.setDragStart(s6);
    var c5 = e1.addComponent(ut.tween.TweenColor);
    var s7 = c5.start();
    s7.r = 172.4798;
    s7.g = 275.84;
    s7.b = 317.9627;
    s7.a = 255;
    c5.setStart(s7);
    var s8 = c5.end();
    s8.r = 255;
    s8.g = 255;
    s8.b = 255;
    s8.a = 255;
    c5.setEnd(s8);
    return [e1];
}

entities.game.ParticlePrefab.name = "ParticlePrefab";
entities.game.ParticlePrefab.load = function(w) {
    var e1 = w.create("ParticleEmitter");
    var e2 = w.create("Particle");
    e1.addComponent(this.Component);
    e2.addComponent(this.Component);
    e1.addComponent(ut.layers.Default);
    e2.addComponent(ut.layers.Default);
    var c1 = e1.addComponent(ut.Core2D.Transform);
    var s1 = c1.localPosition();
    s1.y = -200;
    s1.z = 10;
    c1.setLocalPosition(s1);
    var s2 = c1.localRotation();
    s2.w = 1;
    c1.setLocalRotation(s2);
    var s3 = c1.localScale();
    s3.x = 1;
    s3.y = 1;
    s3.z = 1;
    c1.setLocalScale(s3);
    var c2 = e1.addComponent(ut.Particles.ParticleEmitter);
    c2.setParticle(e2);
    c2.setMaxParticles(300);
    c2.setEmitRate(200);
    var s4 = c2.lifetime();
    s4.start = 0.5;
    s4.end = 1;
    c2.setLifetime(s4);
    var c3 = e1.addComponent(ut.Particles.EmitterBoxSource);
    var s5 = c3.rect();
    s5.width = 50;
    s5.height = 50;
    c3.setRect(s5);
    var c4 = e1.addComponent(ut.Particles.LifetimeScale);
    c4.setCurve(e1);
    var c5 = e1.addComponent(ut.Core2D.Curve);
    c5.setMode(0);
    var a1 = [null, null];
    var s6 = new ut.Core2D.CurveStop();
    s6.value = 10;
    a1[0] = s6;
    var s7 = new ut.Core2D.CurveStop();
    s7.value = 1;
    s7.offset = 1;
    a1[1] = s7;
    c5.setStops(a1);
    var c6 = e2.addComponent(ut.Core2D.Transform);
    var s8 = c6.localPosition();
    c6.setLocalPosition(s8);
    var s9 = c6.localRotation();
    s9.w = 1;
    c6.setLocalRotation(s9);
    var s10 = c6.localScale();
    s10.x = 1;
    s10.y = 1;
    s10.z = 1;
    c6.setLocalScale(s10);
    var c7 = e2.addComponent(ut.Core2D.Sprite2DRenderer);
    c7.setSprite(w.getByName('assets/sprites/Match_Fire'));
    var s11 = c7.color();
    s11.r = 1;
    s11.b = 0.03584909;
    s11.a = 1;
    c7.setColor(s11);
    c7.setBlending(0);
    return [e1, e2];
}

entities.game.SlashPrefab.name = "SlashPrefab";
entities.game.SlashPrefab.load = function(w) {
    var e1 = w.create("SlashEffect");
    e1.addComponent(this.Component);
    e1.addComponent(ut.layers.Default);
    var c1 = e1.addComponent(ut.Core2D.Transform);
    var s1 = c1.localPosition();
    s1.z = 20;
    c1.setLocalPosition(s1);
    var s2 = c1.localRotation();
    s2.w = 1;
    c1.setLocalRotation(s2);
    var s3 = c1.localScale();
    s3.x = 100;
    s3.y = 100;
    s3.z = 1;
    c1.setLocalScale(s3);
    var c2 = e1.addComponent(ut.Core2D.Sprite2DRenderer);
    c2.setSprite(w.getByName('assets/sprites/Match_Slash'));
    var s4 = c2.color();
    s4.r = 1;
    s4.g = 1;
    s4.b = 1;
    s4.a = 1;
    c2.setColor(s4);
    c2.setBlending(0);
    var c3 = e1.addComponent(game.SlashEffect);
    return [e1];
}

entities.game.VictoryGroup.name = "VictoryGroup";
entities.game.VictoryGroup.load = function(w) {
    var e1 = w.create("Match_Victory");
    e1.addComponent(this.Component);
    e1.addComponent(ut.layers.Default);
    var c1 = e1.addComponent(ut.Core2D.Transform);
    var s1 = c1.localPosition();
    s1.y = 311;
    s1.z = 30;
    c1.setLocalPosition(s1);
    var s2 = c1.localRotation();
    s2.w = 1;
    c1.setLocalRotation(s2);
    var s3 = c1.localScale();
    s3.x = 150;
    s3.y = 150;
    s3.z = 1;
    c1.setLocalScale(s3);
    var c2 = e1.addComponent(ut.Core2D.Sprite2DRenderer);
    c2.setSprite(w.getByName('assets/sprites/Match_Victory'));
    var s4 = c2.color();
    s4.r = 1;
    s4.g = 1;
    s4.b = 1;
    s4.a = 1;
    c2.setColor(s4);
    c2.setBlending(0);
    return [e1];
}

